swagger: "2.0"

info:
  version: unversioned
  title: BuildKit

consumes:
  - application/json

produces:
  - application/json

schemes:
  - http
  - https

basePath: /v1

securityDefinitions:
  BasicAuth:
    type: basic
  BearerAuth:
    type: apiKey
    in: header
    name: Bearer

paths:
  /users/{userID}:
    get:
      summary: Fetch a specific user
      operationId: GetUser
      tags:
        - user
      parameters:
        - in: path
          name: userID
          description: A user UUID or slug
          type: string
          required: true
      responses:
        200:
          description: The fetched user details
          schema:
            $ref: "#/definitions/User"
        403:
          description: User is not authorized
          schema:
            $ref: "#/definitions/GenericError"
        default:
          description: Some error unrelated to the handler
          schema:
            $ref: "#/definitions/GenericError"

definitions:
  User:
    type: "object"
    required:
      - "username"
      - "email"
    properties:
      id:
        type: "string"
        format: "uuid"
        readOnly: true
      username:
        type: "string"
        x-isnullable: false
      password:
        type: "string"
        format: "password"
      email:
        type: "string"
        format: "email"
        x-isnullable: false
      created_at:
        type: "string"
        format: "date-time"
        x-isnullable: false
      updated_at:
        type: "string"
        format: "date-time"
        x-isnullable: false

  GenericError:
    description: General error
    type: "object"
    required:
      - "message"
    properties:
      message:
        type: "string"
      documentation_url:
        type: "string"
        format: "uri"
